name: Reviewbot
description: "Automated PR Review for Graylog"
branding:
  icon: "search"
  color: green
inputs:
  prefix:
    description: 'The prefix of the folder where JS/TS files are located'
    required: true
  workingDirectory:
    description: 'The working directory of this action. Same as prefix if not specified'
    required: false
  token:
    description: 'The github token for this action'
    required: true
runs:
  using: "node12"
  main: "dist/index.js"